### PR TITLE
Bulked out code required for demos

### PR DESCRIPTION
**Pull request by w-shackleton**

### CODE REVIEW

**Comment by w-shackleton** [comment]
Build borked by changing travis config in another branch - rebasing

**Comment by Baltoli** [comment]
:+1:

**Comment by w-shackleton** [comment]
derp

**Comment by w-shackleton** [comment]
@Baltoli it's failing here:

``` java
uk.ac.cam.cl.wildpetscience.triton.lib.config.ConfigTest > testConfigRouting FAILED
    java.net.ConnectException at ConfigTest.java:42
```

Any ideas?

**Comment by w-shackleton** [comment]
flaky travis is flaky

**Comment by Baltoli** [comment]
This failure is Travis not us, yeah? :-1:

**Comment by w-shackleton** [comment]
That time, yeah

**Comment by Baltoli** [comment]
:+1:

**Pull request merged**
