### PR TITLE
Added AnalysisDemo to demonstrate output of analysis stage combined with...

### PR DESCRIPTION
**Pull request by w-shackleton**
... other stages

### CODE REVIEW

**Comment by w-shackleton** [comment]
@sashforth to use this, copy one of the other demos but then change `VisualPipelineDemo` to `AnalysisDemo`, then hook up each of the stages to it. `AnalysisDemo` is a `OutputSink` that takes an `Analysis` object that it calls, and draws the other information over the image.

To pass the image and the location into the `AnalysisDemo` you'll need to wrap the motion tracker with a `PassthroughFilter` - see "Location Tracking demo" for an example.

**Comment by w-shackleton** [comment]
This is so cool now we've put it all together!

**Comment by w-shackleton** [comment]
Rebased.

**Comment by sashforth** [comment]
Looks good

**Pull request merged**
