### PR TITLE
Added demo for location tracking

### PR DESCRIPTION
**Pull request by w-shackleton**

### CODE REVIEW

**Comment by w-shackleton** [comment]
@Baltoli tests seem to never be exiting - any ideas why?

**Comment by Baltoli** [comment]
I've submitted a pull request that should allow this to be merged.

**Comment by Baltoli** [comment]
#59 should give us an insight as to why this is failing @w-shackleton - try another dummy commit once it's merged.

**Comment by Baltoli** [comment]
Rebased.

**Comment by w-shackleton** [comment]
Lots of commits here - is this OK to merge?

**Comment by Baltoli** [comment]
Should be - just a rebase adding the commits i think. Worth checking if you're concerned though.

**Pull request merged**
