### PR TITLE
Added Windows compatibility

### PR DESCRIPTION
**Pull request by w-shackleton**
OpenCV has to be installed to C:/opencv

Also added a Bootstrap class for stuff that needs to be done at main() (such as load opencv)

### CODE REVIEW

**Comment by w-shackleton** [comment]
@gavrilavlad this should fix things for you - you'll have to download OpenCV and put it in C:\opencv

**Comment by Baltoli** [comment]
Looks good

**Comment by w-shackleton** [comment]
The way I see it, every main() should start with Bootstrap.init()

**Comment by Baltoli** [comment]
Seems a reasonable way of doing things - will sort mine out tomorrow

**Pull request merged**
