### PR TITLE
Preliminary version of TrackingFilter

### PR DESCRIPTION
**Pull request by gavrilavlad**
Added implementation of a very basic motion tracker: center on motion is
average of all motion points, probability is dependent on the area of
motion (not ideal).

### CODE REVIEW

**Comment by w-shackleton** [comment]
Nice

**Comment by w-shackleton** [comment]
One preliminary comment of mine is that this reacts badly to noise - it works much better on the test videos than my webcam. Is there anything we can do about this or do we have to reduce noise first?
Since noise reduction is expensive I'd recommend trying to deal with noise at the outset.

**Comment by gavrilavlad** [comment]
When I'll add the clustering feature, I think the noise will be removed, because I won't consider for the center of motion any cluster less than a certain size. So most of the motion caused by the noise will not be considered.

**Comment by w-shackleton** [comment]
:+1: as long as it's covered

**Pull request merged**
