### PR TITLE
Changed server test task to depend on Gradle assemble rather than IntelliJ Make

### PR DESCRIPTION
**Pull request by w-shackleton**

### CODE REVIEW

**Comment by Baltoli** [comment]
Looks good.

**Comment by w-shackleton** [comment]
Whenever a new config is created we have to do this - IntelliJ build will sometimes work but we can't depend on that.

**Comment by Baltoli** [comment]
You might want to add a section in the README about it in that case

**Comment by w-shackleton** [comment]
Will do

**Pull request merged**
