### PR TITLE
Serve

### PR DESCRIPTION
**Pull request by Baltoli**
This set of commits pulls together a decent chunk of work on the configuration webpage.

### CODE REVIEW

**Comment by w-shackleton** [comment]
Crikey

**Comment by w-shackleton** [comment]
I'll have a look through but this is massive

**Comment by Baltoli** [comment]
A big chunk is adding bootstrap - that's where a lot of the 31 files come from (as well as some IDE files).

**Comment by w-shackleton** [comment]
Yeah - LGTM

**Pull request merged**
