### PR TITLE
Revert "Initial connect"

### PR DESCRIPTION
**Pull request by sashforth**
Reverts WildPetScience/Triton#148

### CODE REVIEW

**Comment by sashforth** [comment]
Apologies - I should have tried to start the demos before merging this. On starting the Triton Demos:

Exception in thread "main" java.lang.NullPointerException
    at uk.ac.cam.cl.wildpetscience.triton.lib.Bootstrap.init(Bootstrap.java:84)
    at uk.ac.cam.cl.wildpetscience.triton.demo.Demos.main(Demos.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

@Baltoli

**Comment by Baltoli** [comment]
I can't reproduce this at all

**Comment by sashforth** [comment]
I get it by attempting to start the Complete demo (with webserver)

**Comment by rogersnm** [comment]
I get the same error

**Comment by rogersnm** [comment]
body.put("identifier", primary.getAccessData().stringID);

primary.accessData (and thus primary.getAccessData()) is null

**Comment by rogersnm** [comment]
AppConfig primary = AppConfig.getPrimaryConfig();

At line 60 in Bootstrap.java returns a config with null primary.accessData (and also null animalType)

**Comment by rogersnm** [comment]
Presumably because Lib/src/main/resources/config/config.default.json is lacking the relevant data

**Pull request closed without merging**
