### PR TITLE
Stop using containers while the build is broken.

### PR DESCRIPTION
**Pull request by Baltoli**

### CODE REVIEW

**Comment by Baltoli** [comment]
This seems to be the best solution for now - we can figure out containers another time.

**Comment by w-shackleton** [comment]
#50 worked

**Comment by w-shackleton** [comment]
Builds were passing - eating right now but can check in a few mins

**Comment by w-shackleton** [comment]
So I think we are good

**Comment by w-shackleton** [comment]
Yep, not yet fixed.

**Pull request merged**
