### PR TITLE
Added a data queue for infrequent sending; rearranged lots of code

### PR DESCRIPTION
**Pull request by sashforth**

### CODE REVIEW

**Comment by w-shackleton** [comment]
Looks good

**Comment by w-shackleton** [comment]
Tests failed

**Comment by sashforth** [comment]
Issues with adding the fourth argument to the constructor

**Comment by w-shackleton** [comment]
``` java
:Client-PC:compileJava/home/travis/build/WildPetScience/Triton/Client-PC/src/main/java/uk/ac/cam/cl/wildpetscience/triton/demo/LocationPipelineDemo.java:27: error: constructor ConfigData in class ConfigData cannot be applied to given types;
        ConfigData config = new ConfigData(zoneSet, 100, 200);
```

**Pull request closed without merging**
