### PR TITLE
More IDE files generated.

### PR DESCRIPTION
**Pull request by Baltoli**
Based on JetBrains support these files should be shared.

### CODE REVIEW

**Comment by w-shackleton** [comment]
Did you do a Gradle sync?
View -> Tool Windows -> Gradle, then press the sync button that pops up. It seems as if one of these changes will go away after a Gradle sync.

**Comment by w-shackleton** [comment]
I'm on IntelliJ 14.0.2

**Comment by Baltoli** [comment]
After running gradle sync, only misc.xml is changed. Is that what you see?

**Comment by Baltoli** [comment]
I have 14.02 for OS X

**Comment by w-shackleton** [comment]
Yep. Push out again and I'll check if mine likes it.

**Pull request closed without merging**
