### PR TITLE
Configmanager

### PR DESCRIPTION
**Pull request by Baltoli**
This pull request has a lot of skeleton code in it for working with the system config.

### CODE REVIEW

**Comment by w-shackleton** [comment]
Do we want to use boxes? Seems as if polygons would be more flexible.
We could use Apache Commons Math: https://commons.apache.org/proper/commons-math/apidocs/index.html?org/apache/commons/math3/geometry/euclidean/twod/PolygonsSet.html
Also do we want to use a standard logging platform?

**Comment by w-shackleton** [comment]
eg. log4j

**Comment by Baltoli** [comment]
Good question r.e. polygons - my thought is that commons math is a really big / complex library to include for a relatively small gain. It's something we could include in the report as a possible improvement we could make.

w.r.t. logging - yes to using a standard logging library for development logging, but this is for maintaining a set of user-visible log entries (i.e. "Uploaded 1kb of data at X date / time") which is a different sort of goal.

**Comment by w-shackleton** [comment]
OK that's fine

**Pull request merged**
